- galaxyproject.repos
- galaxyproject.slurm
- galaxyproject.galaxy
- geerlingguy.nginx
- natefoo.postgresql_objects
- galaxyproject.postgresql
- galaxyproject.proftpd
- geerlingguy.pip
- galaxyproject.gxadmin
- src: https://github.com/usegalaxy-eu/ansible-role-supervisor
  name: usegalaxy-eu.supervisor
- src: https://github.com/usegalaxy-eu/ansible-certbot
  name: usegalaxy-eu.certbot
- src: https://github.com/galaxyproject/ansible-galaxy-tools.git
  name: galaxyprojectdotorg.galaxy-tools

