- hosts: galaxyservers
  gather_facts: False
  vars:
      galaxy_tools_tool_list_files: [ "prepmet_tool_list.yaml" ]
      galaxy_tools_galaxy_instance_url: http://127.0.0.1:8080/
      galaxy_tools_api_key: 0356f1f8824d49d1c5815b14c976e9bb
      galaxy_server_dir: /srv/galaxy
      galaxy_venv_dir: /srv/galaxy/venv
      galaxy_config_file: /srv/galaxy/config/galaxy.yaml
      install_resolver_dependencies: True
  roles:
      - galaxyprojectdotorg.galaxy-tools

  environment:
          http_proxy: http://alfortproxy.afssa.fr:8080/
          https_proxy: http://alfortproxy.afssa.fr:8080/
          HTTP_proxy: http://alfortproxy.afssa.fr:8080/
          HTTPS_PROXY: http://alfortproxy.afssa.fr:8080/
