- hosts: galaxyservers_test
  gather_facts: False
  vars:
      galaxy_tools_tool_list_files: [ "prepmet_tool_list.yaml" ]
      galaxy_tools_galaxy_instance_url: http://galaxy-gvb-test.anses.fr/
      galaxy_tools_api_key: 1b0f06a3b938b9d0d6fc34eb7f8f00a5
      galaxy_server_dir: /nfs/galaxy_test
      galaxy_venv_dir: /nfs/galaxy_test/venv
      galaxy_config_file: /nfs/galaxy_test/config/galaxy.yaml
      install_resolver_dependencies: True
  roles:
      - galaxyprojectdotorg.galaxy-tools
  environment:
          http_proxy: http://alfortproxy.afssa.fr:8080/
          https_proxy: http://alfortproxy.afssa.fr:8080/
          HTTP_proxy: http://alfortproxy.afssa.fr:8080/
          HTTPS_PROXY: http://alfortproxy.afssa.fr:8080/
